CREATE DATABASE MULTICHAT
GO
USE MULTICHAT
GO

CREATE TABLE CLIENT
(
	 ID INT IDENTITY PRIMARY KEY,
	 USERNAME VARCHAR(30),
	 PASSWORD VARCHAR(30),
	 NAME_INMESSAGE NVARCHAR(30),
	 TYPE_ACTI INT, --0:OFF,1:ON
	 AVT VARBINARY(MAX)
)
GO
--
ALTER TABLE CLIENT 
ADD TYPE_ACTI INT

CREATE TABLE ROOM
(
	ID INT IDENTITY PRIMARY KEY,
	NAME_ROOM NVARCHAR(30),
)
GO
CREATE TABLE MEM_ROOM
(
	IDROOM INT,
	IDCLIENT INT
)
GO
CREATE TABLE MESSAGE
(
	ID INT IDENTITY PRIMARY KEY,
	ADDRESS_MESS INT, --0: CLIENT TO CLIENT; 1:CLIENT TO ROOM
	TYPE_MESSAGE INT, --0: STRING,1: AUDIO,2: FILE,3:EMOJI,V.V.....
)
GO

CREATE TABLE POST
(
	ID INT IDENTITY PRIMARY KEY,
	ID_CLIENT INT,
	CLIENT_POST NVARCHAR(30),
	MESSAGE_POST NVARCHAR(100),
	IMAGE_POST IMAGE
)
GO

CREATE TABLE _MESSAGE
(
	ID INT IDENTITY PRIMARY KEY,
	NAMESEND VARCHAR(30),
	NAMERECEVIE VARCHAR(30),
	CONTENT NVARCHAR(MAX),
	TIME_SEND DATE
)
GO
SELECT * FROM _MESSAGE

INSERT INTO _MESSAGE (NAMESEND,NAMERECEVIE,CONTENT)
VALUES
	('hung','hung22',N'sfsdfsf'),
	('hung22','hung',N'sdssfdfsdfsf'),
	('hung','hung22',N'sdsdfsdfsf'),
	('hung22','hung',N'sddfsf'),
	('hung','hung22',N'sdfsdfsf'),
	('hung','hung22',N'dfsdfsf'),
	('hung22','hung',N'sdfsf'),
	('hung','hung22',N'sdfsf')

DROP TABLE _MESSAGE

----------------DROP TABLE
DROP TABLE CLIENT
DROP TABLE ROOM
---------------CREATE FOREIGN KEY 
ALTER TABLE MEM_ROOM
ADD CONSTRAINT FK_MR_ROON
FOREIGN KEY (IDROOM)
REFERENCES ROOM(ID)

ALTER TABLE MEM_ROOM
ADD CONSTRAINT FK_MR_CLIENT
FOREIGN KEY (IDCLIENT)
REFERENCES CLIENT(ID)

ALTER TABLE POST
ADD CONSTRAINT FK_POST_CLIENT
FOREIGN KEY (ID_CLIENT)
REFERENCES CLIENT(ID)

--------------INSERT-----------------
INSERT INTO CLIENT(USERNAME,PASSWORD,NAME_INMESSAGE,TYPE_ACTI)
VALUES
	('hung','20112002','Nguyễn Minh Hưng',0)
SELECT COUNT(*) FROM CLIENT WHERE USERNAME ='hung' AND PASSWORD='20112002'	

SELECT * FROM CLIENT

CREATE PROCEDURE LOAD_MESS @NAMESEND VARCHAR(30), @NAMEREC VARCHAR(30)
AS
	SELECT * FROM _MESSAGE WHERE (NAMESEND = @NAMESEND AND @NAMEREC = NAMERECEVIE) OR (NAMESEND = @NAMEREC AND NAMERECEVIE = @NAMESEND)

CREATE PROCEDURE INSERT_MESS @NAMESEND VARCHAR(30),@NAMEREC VARCHAR(30),@CONTENT NVARCHAR(MAX)
AS 
	INSERT INTO _MESSAGE (NAMESEND,NAMERECEVIE,CONTENT)
	VALUES
		(@NAMESEND,@NAMEREC,@CONTENT)

EXEC LOAD_MESS 'hung','hung22'
EXEC INSERT_MESS 'hung','hung22',N'minh hung dep trai'
