CREATE DATABASE MULTICHAT
GO
USE MULTICHAT
GO

CREATE TABLE CLIENT
(
	 ID INT IDENTITY PRIMARY KEY,
	 USERNAME VARCHAR(30),
	 PASSWORD VARCHAR(30),
	 NAME_INMESSAGE NVARCHAR(30),
	 TYPE_ACTI INT, --0:OFF,1:ON
	 AVT VARBINARY(MAX)
)
GO
--
ALTER TABLE CLIENT 
ADD TYPE_ACTI INT

CREATE TABLE ROOM
(
	ID INT IDENTITY PRIMARY KEY,
	NAME_ROOM NVARCHAR(30),
)
GO
CREATE TABLE MEM_ROOM
(
	IDROOM INT,
	IDCLIENT INT
)
GO
CREATE TABLE MESSAGE
(
	ID INT IDENTITY PRIMARY KEY,
	ADDRESS_MESS INT, --0: CLIENT TO CLIENT; 1:CLIENT TO ROOM
	TYPE_MESSAGE INT, --0: STRING,1: AUDIO,2: FILE,3:EMOJI,V.V.....
)
GO
----------------DROP TABLE
DROP TABLE CLIENT
DROP TABLE ROOM
---------------CREATE FOREIGN KEY 
ALTER TABLE MEM_ROOM
ADD CONSTRAINT FK_MR_ROON
FOREIGN KEY (IDROOM)
REFERENCES ROOM(ID)

ALTER TABLE MEM_ROOM
ADD CONSTRAINT FK_MR_CLIENT
FOREIGN KEY (IDCLIENT)
REFERENCES CLIENT(ID)
--------------INSERT-----------------
INSERT INTO CLIENT(USERNAME,PASSWORD,NAME_INMESSAGE,TYPE_ACTI)
VALUES
	('hung','20112002','Nguyễn Minh Hưng',0)
SELECT COUNT(*) FROM CLIENT WHERE USERNAME ='hung' AND PASSWORD='20112002'	

SELECT * FROM CLIENT
